library WinUser
  
 4 import: SetTimer
 4 import: MessageBoxA
 0 import: GetModuleHandle
12 import: CreateWindowExA
 1 import: RegisterClassA
 0 import: GetLastError 
 4 import: DefWindowProcA
 4 import: GetMessageA
 5 import: PeekMessageA
 1 import: TranslateMessage
 1 import: DispatchMessage
 2 import: ShowWindow
 2 import: WaitForSingleObject
 1 import: Sleep
 6 import: CreateThread
 1 import: UpdateWindow
 1 import: PostQuitMessage
 2 import: BeginPaint
 2 import: EndPaint
 2 import: LoadCursor
 3 import: FillRect
 3 import: InflateRect
 1 import: SetActiveWindow
 1 import: GetStockObject
 1 import: DestroyWindow
 1 import: CloseWindow
 1 import: GetAsyncKeyState
 1 import: CreateCompatibleDC 
 1 import: CreateCompatibleBitmap 
 2 import: SelectObject 
 9 import: BitBlt 
 1 import: DeleteObject 
 1 import: ReleaseMutex 
 1 import: DeleteDC 
 3 import: CreateMutexA 
 3 import: InvalidateRect 
 1 import: CreatePalette 
 1 import: IsGUIThread
 0 import: DestroyCaret
 1 import: ShowCaret
 1 import: SetWindowTextA
 4 import: CreateCaret 
 4 import: CreateDC 
 2 import: GetDeviceCaps   
 2 import: GetClientRect